#!/usr/bin/python

def build(bld):
      bld.stlib(source       = 'sgd.cc lcsgd.cc',
                name         = 'lcsgd',
                target       = 'lcsgd',
                uselib       = 'eigen')

      bld.program(source     = 'main.cc',
                  name       = 'lcsgd_main',
                  target     = 'lcsgd_main',
                  use        = 'lcsgd')
